In [24]:
!pip install scikit-learn

In [25]:
import pandas as pd
import numpy as np

In [26]:
credit_df = pd.read_csv('../data/Credit_risk_preprocessed.csv')

In [27]:
credit_df.head(10)

clientid  income  age  loan  default
0         1   66155   87  8106        0
1         2   34415   76  6564        0
2         3   57317   91  8020        0
3         4   42709   73  6103        0
4         5   66952   46  8770        1
5         6   24904   85    15        0
6         7   48430   54  5722        0
7         8   24500   60  2971        1
8         9   40654   83  4755        0
9        10   25075   67  1409        0

Оттедлим столбец с метками "default" от остальных данных

In [28]:
credit_df["default"].unique()

array([0, 1], dtype=int64)

In [29]:
x = credit_df.iloc[:,:-1].values
y = credit_df.iloc[:,4].values

In [30]:
print(x)

[[    1 66155    87  8106]
 [    2 34415    76  6564]
 [    3 57317    91  8020]
 ...
 [ 1998 44311    56  5522]
 [ 1999 43756    91  1622]
 [ 2000 69436    84  7378]]


In [31]:
print(y)

[0 0 0 ... 1 0 0]


Разделим данные на выборки: тренировочную и тестовую

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, shuffle=False)

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [34]:
x_test

array([[ 1.73299405, -0.05239999,  1.06186371,  0.99312158],
       [ 1.73547307,  1.58451729,  0.4809832 ,  0.39491061],
       [ 1.7379521 ,  0.62594651,  0.62620332, -1.14628178],
       ...,
       [ 3.2129745 , -0.04623131, -0.89860801,  0.3665331 ],
       [ 3.21545353, -0.0846989 ,  1.64274421, -0.90556221],
       [ 3.21793256,  1.69520691,  1.13447377,  0.97191999]])

In [35]:
len(x_test)

600

In [36]:
len(x_train)

1397

# Метод k-ближайших соседей

In [37]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 5)
clf.fit(x_train, y_train)

KNeighborsClassifier()

In [38]:
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

KNeighborsClassifier()

In [39]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[516   6]
 [ 16  62]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       522
           1       0.91      0.79      0.85        78

    accuracy                           0.96       600
   macro avg       0.94      0.89      0.91       600
weighted avg       0.96      0.96      0.96       600



Accuracy показывает что 96% объектов было верно классифицировано

# Классификатор дерева решений

In [40]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

In [41]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[517   5]
 [  4  74]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       522
           1       0.94      0.95      0.94        78

    accuracy                           0.98       600
   macro avg       0.96      0.97      0.97       600
weighted avg       0.99      0.98      0.99       600



99% объектов было верно классифицировано.

# Наивный байесовский классификатор

In [53]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [54]:
GaussianNB(priors=None, var_smoothing=1e-09)

GaussianNB()

In [55]:
 y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[509  13]
 [ 35  43]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.95       522
           1       0.77      0.55      0.64        78

    accuracy                           0.92       600
   macro avg       0.85      0.76      0.80       600
weighted avg       0.91      0.92      0.91       600



92% объектов было верно классифицировано.

#Метод опорных векторов 

In [56]:
from sklearn import svm

clf = svm.SVC()
clf.fit(x_train, y_train)

SVC()

In [59]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[522   0]
 [ 41  37]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       522
           1       1.00      0.47      0.64        78

    accuracy                           0.93       600
   macro avg       0.96      0.74      0.80       600
weighted avg       0.94      0.93      0.92       600



93% объектов было верно классифицировано.

# Логистическая регрессия

In [61]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression()

In [62]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[510  12]
 [ 21  57]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       522
           1       0.83      0.73      0.78        78

    accuracy                           0.94       600
   macro avg       0.89      0.85      0.87       600
weighted avg       0.94      0.94      0.94       600



94% объектов было верно классифицировано.

# Подбор гиперпараметров

K-ближайших соседей

In [65]:
from sklearn.model_selection import GridSearchCV

from sklearn.neighbors import KNeighborsClassifier

parameters = {'n_neighbors':[i for i in range(10,200,10)]}

knn = KNeighborsClassifier()

clf = GridSearchCV(knn, parameters)
clf.fit(x_train, y_train)
clf.best_params_

{'n_neighbors': 20}

Дерево решений

In [66]:
parameters = {'max_depth':[5,6,7,8,9], 'min_samples_split':[2,3,4]}

tree = tree.DecisionTreeClassifier()

clf = GridSearchCV(tree, parameters)
clf.fit(x_train, y_train)
clf.best_params_

{'max_depth': 9, 'min_samples_split': 3}

 Байесовский

In [67]:
parameters = {'var_smoothing':np.arange(1e-09,6e-09,1e-09)}

temp = GaussianNB()

clf = GridSearchCV(temp, parameters)
clf.fit(x_train, y_train)
clf.best_params_

{'var_smoothing': 1e-09}

Опорные вектора

In [68]:
parameters = {'kernel':['linear','poly','rbf'], 'degree':[2,3,4]}

temp2 = svm.SVC()

clf = GridSearchCV(temp2, parameters)
clf.fit(x_train, y_train)
clf.best_params_

{'degree': 2, 'kernel': 'rbf'}

Логистическая регрессия

In [71]:
parameters = {'solver':['newron-cg','lbfgs'],'multi_class':['auto','ovr','multinomial']}

lr = LogisticRegression()

clf = GridSearchCV(lr, parameters)
clf.fit(x_train, y_train)
clf.best_params_

C:\Users\kgubk\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\kgubk\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgubk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1306, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\kgubk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 434, in _check_solver
    raise ValueError("Logistic Regression supports only solvers in %s, got"
ValueError: Logistic Regression supports only solvers in ['liblinear', 'newton-cg', 'lbfgs', 'sag', 'saga'], got newron-cg.

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\kgubk\anaconda3

{'multi_class': 'multinomial', 'solver': 'lbfgs'}